# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt

CREAR DATASET

data = {
    "Dia": ["D1","D1","D2","D2","D3","D3","D4","D4","D5","D5","D6","D6","D7","D7","D8","D8","D9","D9","D10","D10"],
    "Grupo": ["Control","Experimental"] * 10,
    "Visitantes": [5288,5361,5121,5476,4786,4694,5732,4800,5466,5646,5631,5476,4528,4691,4502,5753,4628,4891,5612,5417],
    "Transacciones": [95,129,92,131,86,113,103,115,98,136,101,131,82,113,81,138,83,117,101,130],
    "Ingreso_total_USD": [27976.15,39420.54,27443.29,39915.69,25922.16,33561.69,30665.34,34817.17,
                          28930.42,40692.57,30230.54,39333.57,24816.19,33762.80,24293.76,
                          42008.75,25315.35,34709.27,29804.55,39769.43],
    "Ingreso_por_visitante": [5.29,7.35,5.36,7.29,5.42,7.15,5.35,7.26,5.30,7.20,5.37,7.19,5.48,7.20,5.40,
                              7.30,5.47,7.10,5.31,7.34],
    "TR_%": [1.8,2.4]*10,
    "Abandono_carrito_%": [70.5,66.2,71.2,66.8,70.1,65.4,71.7,65.9,69.8,67.1,70.9,64.8,
                           69.5,65.3,70.2,65.5,71.9,64.9,72.1,67.5],
    "Diferencial_precio_%": [9.5,3]*10
}

df = pd.DataFrame(data)

# Mostrar dataset
df.head()

# Estadísticas generales
df.describe()

import seaborn as sns

plt.figure(figsize=(8,5))
sns.barplot(data=df, x="Dia", y="TR_%", hue="Grupo")
plt.title("Tasa de Conversión por Día y Grupo")
plt.show()

plt.figure(figsize=(8,5))
sns.lineplot(data=df, x="Dia", y="Ingreso_por_visitante", hue="Grupo", marker="o")
plt.title("Ingreso por Visitante (Control vs Experimental)")
plt.show()